version: '2.2'

services:
  wintercms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wintercms_app
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - APP_ENV=docker
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal  
      - DB_PORT=3307  
      - DB_DATABASE=wintercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PHP_MEMORY_LIMIT=-1
    depends_on:
      db:
        condition: service_healthy 
    mem_limit: 4g
    command: sh -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: wintercms_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: wintercms
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=root", "--execute=SHOW DATABASES;"]
      interval: 3s
      timeout: 1s
      retries: 5

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
