version: '2.2'

services:
  wintercms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wintercms_app
    ports:
      - "8080:8000"
    environment:
      - APP_ENV=docker
      - DB_CONNECTION=mysql
      - DB_HOST=172.19.0.2 
      - DB_PORT=3306
      - DB_DATABASE=wintercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PHP_MEMORY_LIMIT=-1 
    depends_on:
      - mariadb
    mem_limit: 4g

  mariadb:
    image: mariadb:10.4
    container_name: wintercms_db
    command: --default-authentication-plugin=mysql_native_password --max-connections=200 --wait_timeout=600 --interactive_timeout=600
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=root", "--execute=SHOW DATABASES;"]
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      - MYSQL_DATABASE=wintercms
      - MYSQL_ROOT_PASSWORD=root